### PR TITLE
Fix sending payloads larger than 65,519 bytes

### LINKED ISSUE #7: plaintext payloads larger than 65,519 bytes will fail to decrypt
Because the max length of a Noise message is 65,535 bytes, including 16 bytes of AEAD authentication data, plaintext messages larger than 65,519 bytes need to be split up into smaller chunks before encrypting.  Otherwise, the encrypted payloads will end up being prefixed with the wrong length (since the length-prefixes max out at 65,535) and decryption will fail.

https://github.com/libp2p/go-libp2p-noise/pull/10 fixes this same issue in the go implementation, if that's helpful for reference.

### PR DESCRIPTION
**Pull request by morrigan**
Resolves #7

### CODE REVIEW

File: src/crypto.ts [hunk 1]
```diff
@@ -1,17 +1,27 @@
...
   (source: Iterable<Uint8Array>): AsyncIterableIterator<Uint8Array>;
 }
 
+const maxPlaintextLength = 65519;
+
 // Returns generator that encrypts payload from the user
 export function encryptStream(handshake: Handshake): ReturnEncryptionWrapper {
   return async function * (source) {
     for await (const chunk of source) {
       const chunkBuffer = Buffer.from(chunk);
```
Comment (mpetrunic) [inline src/crypto.ts]: I'm pretty sure this is creating large overhead because it's allocating new memory and copy chunk data.
I think following code reuses existing memory:
```javascript
Buffer.from(chunk.buffer, chunk.byteOffset, chunk.length)
```

Ref: https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_arraybuffer_byteoffset_length

File: src/crypto.ts [hunk 2]
```diff
@@ -22,8 +32,17 @@ export function decryptStream(handshake: Handshake): ReturnEncryptionWrapper {
...
```
Comment (mpetrunic) [inline src/crypto.ts]: same as above

File: test/utils.ts [hunk 3]
```diff
@@ -11,3 +12,15 @@ export function getKeyPairFromPeerId(peerId: PeerId): KeyPair {
     publicKey: peerId.marshalPubKey(),
   }
 }
+
+export function getRandomBuffer(size: number) : bytes {
```
Comment (mpetrunic) [inline test/utils.ts]: exists in bcrypto
